version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mafia_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mafia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mafia_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mafia_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mafia_network
    restart: unless-stopped

  backend:
    build: .
    container_name: mafia_backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: mafia
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - mafia_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  mafia_network:
    driver: bridge